---
  - name: Create managed disk
    azure_rm_manageddisk:
      # subscription_id: "{{ subscription_id }}"
      # tenant: "{{ tenant }}"
      # client_id: "{{ client_id }}"
      # secret: "{{ secret }}"
      name: "{{ resource_config.disk_name }}"
      resource_group: "{{ resource_group.resource_group }}"
      disk_size_gb: "{{ resource_config.disk_size }}"


  - name: Mounting disk to VM
    azure_rm_manageddisk:
      # subscription_id: "{{ subscription_id }}"
      # tenant: "{{ tenant }}"
      # client_id: "{{ client_id }}"
      # secret: "{{ secret }}"
      name: "{{ resource_config.disk_name }}"
      resource_group: "{{ resource_config.resource_group }}"
      disk_size_gb: "{{ resource_config.disk_size }}"
      managed_by: "{{ vm_name }}"
      attach_caching: read_only