---
 - name: To Detach a disk
   ec2_vol:
      # aws_access_key: "{{ aws_access_key | b64decode }}"
      # aws_secret_key: "{{ aws_secret_key | b64decode }}"
      region: "{{ resource_config.region }}"
      id: "{{ item }}"
      instance: None
   loop: "{{ resource_config.volume_ids }}"

 - name: To delete a volume
   ec2_vol:
      # aws_access_key: "{{ aws_access_key | b64decode }}"
      # aws_secret_key: "{{ aws_secret_key | b64decode }}"
      region: "{{ resource_config.region }}"
      id: "{{ item }}"
      state: absent
   loop: "{{ resource_config.volume_ids }}"
