---
 - name: To power on EC2 instance.
   ec2:
      # aws_access_key: "{{ aws_access_key | b64decode }}"
      # aws_secret_key: "{{ aws_secret_key | b64decode }}"
      instance_ids: "{{ resource_config.instance_ids }}"
      region: "{{ resource_config.region }}"
      state: running
      wait: True
      assign_public_ip: yes

  